apiVersion: v1
kind: Service
metadata:
  labels:
    app: service1
  name: service1
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: service1
status:
  loadBalancer: {}
