apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service1
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  strategy: {}
  template:
    metadata:
      labels:
        app.network/avl-net: "true"
        app: service1
    spec:
      containers:
        - image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          name: service1
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
