apiVersion: v1
kind: Service
metadata:
  labels:
    app: service2
  name: service2
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    app: service2
status:
  loadBalancer: {}
