apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: avl-net
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.network/avl-net: "true"
  podSelector:
    matchLabels:
      app.network/avl-net: "true"
